name: Subtree Sync

on:
  workflow_call:
    inputs:
      matrix:
        description: >
          JSON array of objects, each containing
          "targetRepo" (format: "owner/repo") and "packagePath" fields.
          Example: [
            {"targetRepo": "owner/repo1", "packagePath": "packages/foo"},
            {"targetRepo": "owner/repo2", "packagePath": "packages/bar"}
          ]
        required: true
        type: string
      target-branch:
        description: 'Target branch name'
        required: false
        type: string
        default: main
    secrets:
      sync-token:
        description: 'Personal access token with repo permissions'
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(inputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.sync-token }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add remote repository
        run: |
          git remote add target-repo https://x-access-token:${{ secrets.sync-token }}@github.com/${{ matrix.targetRepo }}.git

      - name: Push subtree to standalone repo
        run: |
          git subtree push --prefix=${{ matrix.packagePath }} target-repo ${{ inputs.target-branch }}

      - name: Success notification
        run: |
          echo "✅ Successfully synced ${{ matrix.packagePath }} to ${{ matrix.targetRepo }}"
